### ISSUE TITLE
La conexion con Telegram no funciona

### ISSUE THREAD

**Issue by jnunesvazquez** [jnunesvazquez/Telegram_Bot#1]

**Comment by bmartinezparedes** [comment]
Faltaba directorio llamado "kotlin" que tiene que auto crearse y no lo hizo, por eso daba fallo. Se soluciona en el comit ->  a562ffc62a9f0ae857b72a8fc54b20f198cbec41 . Otro error menor es que se puso "bot.startPolling()" dentro de bot cuando debería ir fuera. También es un dato interesante y que debería haberse dicho en clase es que cada vez que queramos que se actualice el bot hay que  arrancar el programa. Espero que se tenga esto en cuenta para la nota, porque llevo varios días sin saber porque no me funcionaba.
